ssl:
  cert: certFile-or-pemString
  key: certKeyFile-or-pemString
  ca:
    - caFile-or-pemString-1
    - caFile-or-pemString-2
    # ...
    - caFile-or-pemString-N
  # crl:
  #   - crlFile-or-pemString-1
  #   - crlFile-or-pemString-2
  #   # ...
  #   - crlFile-or-pemString-N
  # serverAdmin: kaka@test
  # documentRoot: /www
  # logLevel: "info ssl:warn"
  # client:
  #   verify: require
  #   depth: 10
  # options:
  #   - +FakeBasicAuth
  #   - +ExportCertData
  #   - +StrictRequire
  # sections:
  #   filesMatch: |
  #     <FilesMatch "\.(cgi|shtml|phtml|php)$">
  #       SSLOptions +StdEnvVars
  #     </FilesMatch>
  #   directory: |
  #     <Directory /usr/lib/cgi-bin>
  #       SSLOptions +StdEnvVars
  #     </Directory>
  #   browserMatch: |
  #     BrowserMatch "MSIE [2-6]" \
  #     nokeepalive ssl-unclean-shutdown \
  #     downgrade-1.0 force-response-1.0
  #   other: |
  #     ... other sections that need to go here ...

modules:
  # If using inc:${absolutePath} here, then the contents will be used for the .conf file.
  # Must use the other syntax to provide the contents of both files
  module-1: boolean-or-inc:${absolutePath}
  module-2:
    enabled: boolean
    files:
      # use "conf" for the .conf file, "load" for the .load file, etc....
      conf: |
        contents of the module's configuration (can also use inc:${absolutePath} here)
      load: |
        contents of the module's load statement (if not given, the existing load file will be used,
        can also use inc:${absolutePath} here)
  # ...
  module-N: ...

sites:
  site-1: boolean-or-inc:${absolutePath}
  site-2:
    enabled: boolean
    files:
      conf: |
        contents of the site configuration (can also use inc:${absolutePath} here)
  # ...
  site-N: ...

confs:
  conf-1: boolean-or-inc:${absolutePath}
  conf-2:
    enabled: boolean
    files:
      conf: |
        contents of the additional configuration (can also use inc:${absolutePath} here)
  # ...
  conf-N: ...
