ssl:
  # serverAdmin: kaka@test
  # documentRoot: /www
  # logLevel: "info ssl:warn"
  # client:
  #   verify: require
  #   depth: 10
  # options:
  #   - +FakeBasicAuth
  #   - +ExportCertData
  #   - +StrictRequire
  cert: certFile-or-base64
  key: certKeyFile-or-base64
  ca:
    - caFile-or-base64-1
    - caFile-or-base64-2
    # ...
    - caFile-or-base64-N

modules:
  module-1: boolean
  module-2:
    enabled: boolean
    conf: |
      contents of the module's configuration
  # ...
  module-N: ...

sites:
  site-1: boolean
  site-2:
    enabled: boolean
    conf: |
      contents of the site configuration
  # ...
  site-N: ...

confs:
  conf-1: boolean
  conf-2:
    enabled: boolean
    conf: |
      contents of the additional configuration
  # ...
  conf-N: ...
