#!/bin/bash

#
# TODO: Process config.yaml, then start the server
#

#
# TODO: there must be a /reload command that causes the apache process to reload the configuration
#

exec /usr/bin/supervisord -n
