#!/bin/bash

# Overlay the configurations present in /conf to /etc/apache2
# ( cd "${CONF_SRC}" && tar -cf - . ) | tar -C "${CONF_TGT}" -xvf -

#
# TODO: Enable sites, modules, configurations, etc., per the environment
# TODO: devise a means to do this cleanly without too much effort
# TODO: SSL will be pre-configured to use the cert at /ssl/crt, the key at /ssl/key,
#       and the ca at /ssl/ca
# TODO: Other specific SSL configurations can be handled via environment

exec /usr/bin/supervisord -n
